FROM continuumio/miniconda3:24.5.0-0 AS build

RUN \
  conda install conda-libmamba-solver

RUN \
  echo -e > ~/.condarc '\
solver: libmamba\n\
channels:\n\
  - umccr\n\
  - conda-forge\n\
  - bioconda\n\
  - defaults'

COPY ./conda/env/bolt_env.yml /tmp/
RUN \
  conda env update --prefix /env/ --file /tmp/bolt_env.yml

RUN \
  conda install --prefix /env/ \
    'r-gpgr ==2.3.1' \
    'r-sigrap ==0.1.1' \
    'bioconductor-bsgenome.hsapiens.ucsc.hg38 ==1.4.5' \
    'bioconductor-txdb.hsapiens.ucsc.hg38.knowngene ==3.16.0' \
    'bioconductor-genomeinfodbdata ==1.2.9'

# NOTE(eval): swap conda's published r-gpgr 2.3.1 for gpgr PR #102's branch (commit
# 4f0cf477), so this test image exercises the real dragen_hrd-optional/%||% fix
# instead of the published release. Deps already resolved by the conda install
# above, so install with dependencies=FALSE to avoid conda/CRAN version conflicts.
RUN \
  conda install --prefix /env/ r-remotes && \
  conda run --prefix /env/ Rscript -e "remotes::install_github('umccr/gpgr@4f0cf4779a9f9cd7e76108ca4dfdd7d024fc9d73', dependencies = FALSE, upgrade = 'never')"

COPY ./ /tmp/bolt/
RUN \
  conda run --prefix /env/ pip install --no-deps /tmp/bolt/

RUN \
  conda install --prefix /env/ bash

FROM quay.io/bioconda/base-glibc-busybox-bash:2.1.0

COPY --from=build /env/ /env/

ENV PATH="/env/bin:${PATH}"
ENV LD_LIBRARY_PATH="/env/lib/"
