FROM continuumio/miniconda3:24.5.0-0 as build

RUN \
  conda install conda-libmamba-solver

RUN \
  echo -e > ~/.condarc '\
solver: libmamba\n\
channels:\n\
  - conda-forge\n\
  - bioconda\n\
  - defaults'

COPY ./conda/env/bolt_env.yml /tmp/
RUN \
  conda env update --prefix /env/ --file /tmp/bolt_env.yml

RUN \
  conda install --prefix /env/ git

RUN \
  conda run --prefix /env/ pip install 'multiqc ==1.15' && \
  conda run --prefix /env/ pip install 'git+https://github.com/umccr/multiqc_template@v0.0.3'

COPY ./ /tmp/bolt/
RUN \
  conda run --prefix /env/ pip install --no-deps /tmp/bolt/

RUN \
  conda install --prefix /env/ bash

FROM gcr.io/distroless/base-debian11:latest

# Copy BusyBox binaries; Nextflow uses /bin/bash to execute process shell code
COPY --from=busybox:1.35.0-uclibc /bin/ /bin/
COPY --from=build /env/bin/bash /bin/

# Copy Conda env
COPY --from=build /env/ /env/

ENV PATH="/env/bin:${PATH}"
ENV LD_LIBRARY_PATH="/env/lib/:${LD_LIBRARY_PATH}"
